minor improvements

diff --git a/ExTeX/build b/ExTeX/build
--- a/ExTeX/build
+++ b/ExTeX/build
@@ -1,43 +1,63 @@
 #!/bin/sh
-# This file should be executable.
+#------------------------------------------------------------------------------
+# Copyright (C) 2004 The ExTeX Group
+#
+# This library is free software; you can redistribute it and/or modify it under
+# the terms of the GNU Lesser General Public License as published by the Free
+# Software Foundation; either version 2.1 of the License, or (at your option)
+# any later version.
+#
+# This library is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
+# details.
+#
+# You should have received a copy of the GNU Lesser General Public License
+# along with this library; if not, write to the Free Software Foundation, Inc.,
+# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
+#
+#------------------------------------------------------------------------------
+# THIS FILE SHOULD BE EXECUTABLE.
+#------------------------------------------------------------------------------
 echo
 echo "ExTeX Build System"
-echo "----------------"
+echo "------------------"
 echo
 
 if [ "$JAVA_HOME" = "" ] ; then
-  echo "ERROR: JAVA_HOME not found in your environment."
-  echo
-  echo "Please, set the JAVA_HOME variable in your environment to match the"
-  echo "location of the Java Virtual Machine you want to use."
-  exit 1
+    echo "ERROR: JAVA_HOME not found in your environment."
+    echo
+    echo "Please, set the JAVA_HOME variable in your environment to match the"
+    echo "location of the Java Virtual Machine you want to use."
+    exit 1
 fi
 
 # OS specific support.  $var _must_ be set to either true or false.
 cygwin=false;
 case "`uname`" in
-  CYGWIN*) cygwin=true ;;
+    CYGWIN*) cygwin=true ;;
 esac
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
 if $cygwin ; then
-  [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+    [ -n "$JAVA_HOME" ] &&
+        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
 fi
 
 LIBDIR=lib
 
-LOCALCLASSPATH=$JAVA_HOME/lib/tools.jar
-LOCALCLASSPATH=$LOCALCLASSPATH:$JAVA_HOME/lib/classes.zip
+LOCALCLASSPATH=.
+#LOCALCLASSPATH=$JAVA_HOME/lib/tools.jar
+#LOCALCLASSPATH=$LOCALCLASSPATH:$JAVA_HOME/lib/classes.zip
 
 # jar-Dateien
-for i in $LIBDIR/*.jar ; do
-        LOCALCLASSPATH=$LOCALCLASSPATH:$i
-done
+#for i in $LIBDIR/*.jar ; do
+#    LOCALCLASSPATH=$LOCALCLASSPATH:$i
+#done
 
 # jar-Dateien
 for i in lib.develop/*.jar ; do
-        LOCALCLASSPATH=$LOCALCLASSPATH:$i
+    LOCALCLASSPATH=$LOCALCLASSPATH:$i
 done
 
 # export $LOCALCLASSPATH
@@ -50,8 +70,8 @@ ANT_HOME=$LIBDIR
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
-  JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
-  LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
+    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+    LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
 fi
 
 echo
